### ISSUE TITLE
Unclear whether there's a way to use minio with Amazon S3

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/docs-minio#11]
[Judging by the developer guide](https://docs.pivotal.io/partners/minio/developer-guide-create.html), the only storage backing options are either VM disks, or using a gateway for either `Azure` or `GCP`. Although minio is compatible with s3 APIs, it's unclear whether a minio service instance can use Amazon s3 itself as a backing store.

Can the PCF minio tile use Amazon s3 as a gateway/backing store?

**Comment by aegershman** [comment]
We're exploring our options of how we can consolidate and simplify both the APIs for blob storage (s3-compatibility) as well as operationalizing things. We're curious how we can get the benefits of s3-compliant blob storage, while not having to maintain both minio and an s3 broker tile. We're curious what can be done to allow application instances to be brokered to minio, but ultimately have minio gateway through to different storage mediums, including aws-s3 itself.

**Comment by krishnasrinivas** [comment]
@aegershman thanks for the explanation. Can you open an issue here: https://github.com/minio/minio-pcf-adapter/issues linking the new issue to this issue? It will be easier to track as we don't keep an eye on this repo.

**Comment by aegershman** [comment]
Not a problem, my bad. Thanks for the responsiveness, I appreciate it
